version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./apps/backend/.env
    volumes:
      - ./apps/backend:/usr/src/app
      - ./apps/backend/prisma:/usr/src/app/prisma
    command: npm run start:dev
    working_dir: /usr/src/app
